# Generated by Django 5.1 on 2024-08-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velzonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True},
        ),
    ]
